mysql:
  image: mysql:latest
  volumes:
    - ./mysql/data/library-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    - ./mysql/data/library.sql:/docker-entrypoint-initdb.d/data.sql
  command: --default-authentication-plugin=mysql_native_password
  ports: 
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: library
    MYSQL_USER: library
    MYSQL_PASSWORD: library